version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: booking-db
    environment:
      POSTGRES_USER: ${DB_USER:-bookinguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bookingpass}
      POSTGRES_DB: ${DB_NAME:-bookingdb}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-bookinguser}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
